### ISSUE TITLE
Pick a cat picture to add to your profile bio

### ISSUE THREAD

**Issue by MJLA77** [jjhp516/Sass-Assignment-Group-1#21]
please pick a picture from https://unsplash.com/ to add to our profile blog.  - the picture will be linked with our bio.

**Comment by jjhp516** [comment]
My suggestions:

https://unsplash.com/photos/1l2waV8glIQ

https://unsplash.com/photos/NodtnCsLdTE

https://unsplash.com/photos/6nve1xdFQHQ

**Comment by zashurazxz** [comment]
the first picture is our cat hero image (there are some images in the master file in the img folder)
